def sign_count(text: str)-> int:
	return len(text)

text = """
Mein Forschungsgebiet ist zunächst der Entwurf und die formale Verifikation von eingebetteten, cyberphysischen, hybriden Systemen. Ich habe mich zuletzt in diesem Gebiet mit der formalen Verifikation der Verhaltensäquivalenz von eingebetteten Systemen beschäftigt, die mittels formal definierter datenflussorientierter, hybrider Modellsprachen (Simulink) spezifiziert wurden. Einen weiteren Schwerpunkt bildet mein Forschungsinteresse in Security, den ich durch meine umfangreiche Unternehmenstätigkeit in dem Bereich aufgebaut habe. In meiner letzten Tätigkeit bei Zalando habe ich maßgeblich ein System entworfen, das mittels Machine Learning das beobachtete Verhalten von Bots (Programmen, die eine Plattform anzugreifen versuchen) klassifiziert und entsprechende Gegenmaßnahmen trifft.
Mein Forschungsinteresse gilt somit insgesamt dem Design und der formalen Verifikation sicherer (safe and secure) Systeme. Dabei betrachte ich sowohl die Verwendung von KI-Methoden zur Unterstützung klassischer Methoden (z.B. Einsatz von Machine Learning zur Mustererkennung in statischen Analysen, zur Generierung von Vorschlägen für die Verifikation oder zur Exploration von Schwachstellen mittels KI) als auch die Erweiterung dieser Methoden, um mit Systemen, die KI-Komponenten beinhalten, umgehen zu können.
In jüngster Zeit habe ich zudem begonnen, ethische und sozio-technische Erwägungen mit in die Spezifikation und das Design der Systeme einfließen zu lassen.

Eine der Stärken der HWR ist die Interdisziplinarität: Wirtschaftswissenschaftler, Rechtswissenschaftler, Mathematiker, Ingenieure und Informatiker arbeiten an der HWR. Die Interdisziplinarität setzt die HWR in eine einzigartige Position, Probleme der Gesellschaft, die inhärent interdisziplinär sind, anzugehen. Dies hebt uns von rein technischen Hochschulen und Universitäten ab. Gerade die zunehmende Bedeutung von KI, deren Umgang und Auswirkungen auf die Gesellschaft, hat ein großes Potenzial für Forschung, das vor allem von interdisziplinären Teams innerhalb der HWR gehebelt werden kann. Dies wurde strategisch auch erkannt und in diesem Jahr habe ich zusammen mit Kollegen aus FB 1 und 2 ein an diesen Antrag angelehnten Projektantrag im Rahmen der DFG-Förderung Forschungsimpulse gestellt. Mit diesem Antrag haben wir uns innerhalb der HWR als einzige Gruppe durchgesetzt und dieser ist dann, mit der Bekundung der Unterstützung des Antrages durch die Hochschulleitung bei der DFG gestellt worden. Dies zeigt, dass die Inhalte dieses Forschungsprojektes mit der Strategie der HWR übereinstimmen und geeignet ist, die Stärken der HWR weiter auszubauen.

Darüber hinaus existieren bereits interdisziplinäre Projekte im Fachbereich 2 aus dem Bereich embedded systems: WInf, Inf, Facility Management und perspektivisch BWL / Industrie werden in Forschung und Lehre in dem Bereich zusammenarbeiten. Zum anderen planen wir das Einreichen eines BMBF-Antrages HAW-Forschungsraum Qualifizierung zur Entwicklung des Bereiches.
"""

print(sign_count(text))
